BirdCageShop/BirdCageShop/Pages/Users/Accessory.cshtml.cs
using BusinessObjects.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;

namespace BirdCageShop.Pages.Users
{
    public class AccessoryModel : PageModel
    {
        /// <summary>
        /// OnGet View List of Accessory
        /// </summary>
        /// 


        private readonly IProductRepository _proRepos;
        private readonly IUserRepository _userRepo;
        private readonly ICartRepository _cartRepo;
        private readonly IAccessoryRepository _accessoryRepo;
        [BindProperty(SupportsGet = true)]



        public int pageNo { get; set; } = 1; //PageNo
        public int totalProduct { get; set; } //Count
        public int pageSize { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SortBy { get; set; }


        public static int productID { get; set; }
        public List<Accessory> Data { get; set; }
        public AccessoryModel()
        {
            _proRepos = new ProductRepository();
            _userRepo = new UserRepository();
            _cartRepo = new CartRepository();
            _accessoryRepo = new AccessoryRepository();

        }
        public int pOpt0 { get; set; }
        public int pOpt1 { get; set; }
        public int pOpt2 { get; set; }
        public int pOpt3 { get; set; }
        public int pOpt4 { get; set; }
        public IList<Accessory> pagedProducts { get; set; } //Product
        public List<Accessory> accessories { get; set; }
        public void OnGet(int p = 1, int s = 6)
        {
            pOpt0 = _proRepos.FillterProduct(0).Count();
            pOpt1 = _proRepos.FillterProduct(1).Count();
            pOpt2 = _proRepos.FillterProduct(2).Count();
            pOpt3 = _proRepos.FillterProduct(3).Count();
            pOpt4 = _proRepos.FillterProduct(4).Count();
            try
            {
                accessories = _proRepos.GetAccessories();
                if (accessories != null)
                {
                    if (!string.IsNullOrEmpty(SortBy))
                    {
                        switch (SortBy)
                        {
                            case "Quantity":
                                pagedProducts = _proRepos.getAccessoryPages(p, s).OrderByDescending(p => p.AccessoryQuantity).ToList();
                                break;
                            case "Price":
                                pagedProducts = _proRepos.getAccessoryPages(p, s).OrderByDescending(p => p.AccessoryPrice).ToList();
                                break;
                            default:
                                pagedProducts = _proRepos.getAccessoryPages(p, s);
                                break;
                        }
                    }
                    else
                    {
                        pagedProducts = _proRepos.getAccessoryPages(p, s);
                    }
                }

                totalProduct = accessories.Count;
                pageSize = s;
                pageNo = p;
                Page();
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }

        }
        public IActionResult OnPost(int accessoryID)
        {
            pOpt0 = _proRepos.FillterProduct(0).Count();
            pOpt1 = _proRepos.FillterProduct(1).Count();
            pOpt2 = _proRepos.FillterProduct(2).Count();
            pOpt3 = _proRepos.FillterProduct(3).Count();
            pOpt4 = _proRepos.FillterProduct(4).Count();
            try
            {
                if (HttpContext.Session.GetInt32("userID") == null)
                {
                    TempData["errorMessage"] = "Hãy đăng nhập trước khi thêm vào giỏ của bạn nhé. Mình chuyển đến trang đăng nhập giúp bạn rồi nè";
                    return RedirectToPage("/Login/Index");
                }
                else
                {
                    int userID = (int)HttpContext.Session.GetInt32("userID");
                    int result = _cartRepo.addProductToCart(accessoryID, 1,1);
                    if (result == 0)
                    {
                        TempData["errorMessage"] = "Có vẻ điều gì đó đã xảy ra. Không thể thêm vào giỏ hàng";
                        return RedirectToPage("./Shop");
                    }
                    else
                    {
                        TempData["successMessage"] = "Thêm vào giỏ hàng thành công";
                        return RedirectToPage("./Shop");
                    }
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "Somthing unexpected happend!" + ex.Message; return Page();
            }

        }
        public void OnPostSearch(string productName)
        {
            pOpt0 = _proRepos.FillterProduct(0).Count();
            pOpt1 = _proRepos.FillterProduct(1).Count();
            pOpt2 = _proRepos.FillterProduct(2).Count();
            pOpt3 = _proRepos.FillterProduct(3).Count();
            pOpt4 = _proRepos.FillterProduct(4).Count();
            pagedProducts = _proRepos.GetAccessoryByName(productName);
            if (pagedProducts == null)
            {
                OnGet();
            }
        }
        public void OnPostFilterPrice()
        {
            pOpt0 = _proRepos.FillterProduct(0).Count();
            pOpt1 = _proRepos.FillterProduct(1).Count();
            pOpt2 = _proRepos.FillterProduct(2).Count();
            pOpt3 = _proRepos.FillterProduct(3).Count();
            pOpt4 = _proRepos.FillterProduct(4).Count();
            int opt = int.Parse(Request.Form["priceRange"]);
            var list = _accessoryRepo.FillterProduct(opt);
            if (list == null)
            {
                OnGet();
            }
            else
            {
                pagedProducts = list;
                Page();
            }
        }

    }
}

BirdCageShop/BirdCageShop/Pages/Users/AccessoryDetail.cshtml.cs
using BusinessObjects.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Repository;
using System.Collections.Generic;

namespace BirdCageShop.Pages.Users
{

    public class AccessoryDetailModel : PageModel
    {
        private readonly IProductRepository _proRepo;
        private readonly IUserRepository _userRepo;
        private readonly ICartRepository _cartRepo;
        private readonly IFeedbackRepository _feedbackRepo;
        public AccessoryDetailModel()
        {
            _proRepo = new ProductRepository();
            _userRepo = new UserRepository();
            _cartRepo = new CartRepository();   
            _feedbackRepo = new FeedbackRepository();
        }
        public static int accessoryID { get; set; }
        public Accessory accessory { get; set; }
        public Tuple<int, int> getFeedbackStatic { get; set; }
        public List<Product> getPopularList { get; set; }
        public List<FeedbackItem> GetFeedbackItems { get; set; }
        public string ErrorMessage { get; set; }
        public IActionResult OnGet(int accessoryId)
        {
            try
            {
                accessoryID = accessoryId;
                accessory = new Accessory();
                accessory = _proRepo.getDetailAccessoryByID(accessoryID);
                getFeedbackStatic = _proRepo.getRatingAccessory(accessoryID);
                getPopularList = _proRepo.getListProductTrendingForUser();
                GetFeedbackItems = _feedbackRepo.getListFeedbackByAccessoryID(accessoryId);
                if (accessory == null)
                {
                    return RedirectToAction("../Error");

                }
                else
                {
                    return Page();
                }
            }
            catch (Exception ex)
            {

                return RedirectToAction("../Error");
            }
        }

        public IActionResult OnPost()
        {
            try
            {
                if (HttpContext.Session.GetInt32("userID") == null)
                {
                    TempData["errorMessage"] = "Hãy đăng nhập trước khi thêm vào giỏ của bạn nhé. Mình chuyển đến trang đăng nhập giúp bạn rồi nè";
                    return RedirectToPage("../Login/Index");
                }
                else
                {
                    
                    int userID = (int)HttpContext.Session.GetInt32("userID");
                    var cart = _cartRepo.showCart();
                    int result = _cartRepo.addProductToCart(accessoryID, 1,1);
                    if (result == 0)
                    {
                        TempData["errorMessage"] = "Có vẻ điều gì đó đã xảy ra. Không thể thêm vào giỏ hàng";
                        return RedirectToPage("./Shop");
                    }
                    else
                    {
                        TempData["successMessage"] = "Thêm vào giỏ hàng thành công";
                        return RedirectToPage("./Shop");
                    }
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "Somthing unexpected happend!" + ex.Message; return RedirectToPage("./Error");
            }

        }
        
    }
}

BirdCageShop/BirdCageShop/Pages/Users/Comparision.cshtml.cs
using BusinessObjects.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Repository;

namespace BirdCageShop.Pages.Users
{
    public class ComparisionModel : PageModel
    {
        private IProductRepository _proRepo;
        private ICartRepository _cartRepo;
        public List<Product> comparePro;
        public ComparisionModel()
        {
            _cartRepo = new CartRepository();
            _proRepo = new ProductRepository();
            comparePro = new List<Product>();
        }
        public void OnGet()
        {
            int prod1 = HttpContext.Session.GetInt32("pID1") ?? 0;
            int prod2 = HttpContext.Session.GetInt32("pID2") ?? 0;
            if(prod1 != 0 && prod2 != 0)
            {
                comparePro = _proRepo.comparisionProduct(prod1,prod2);
            }
            else
            {
                comparePro = new List<Product>(); 
            }
        }
        public void OnPost(int pID)
        {
            int prod1 = HttpContext.Session.GetInt32("pID1") ?? 0;
            int prod2 = HttpContext.Session.GetInt32("pID2") ?? 0;
            if (pID == prod1) HttpContext.Session.SetInt32("pID1", 0);
            else if (pID == prod2) HttpContext.Session.SetInt32("pID2", 0);
            OnGet();
            Page();
        }

    }
}

BirdCageShop/BirdCageShop/Pages/Users/Customized.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;

namespace BirdCageShop.Pages.Users
{
    public class CustomizedModel : PageModel
    {
        private readonly IProductRepository _proRepos;
        private readonly ICartRepository _cartRepo;
        private readonly ICategoryRepository _catRepo;

        [BindProperty]
        public int cageType { get; set; }
        [BindProperty]
        public int lidCage { get; set; }
        [BindProperty]
        public int barCageType { get; set; }
        [BindProperty]
        public int barCageCount { get; set; } = 50;
        [BindProperty]
        public int doorCageType { get; set; }
        [BindProperty]
        public int baseCage { get; set; }
        [BindProperty]
        public int orderPrice { get; set; }
        [BindProperty]
        public int expenseMachining { get; set; }
        public IList<BusinessObjects.Models.Category> Categories { get; set; }
        public CustomizedModel()
        {
            _proRepos = new ProductRepository();
            _cartRepo = new CartRepository();
            _catRepo = new CategoryRepository();
        }



        public void OnGet()
        {
            Categories = _catRepo.GetAll().ToList();
        }
        public IActionResult OnPost()
        {
            doorCageType = Int32.Parse(Request.Form["doorCage"]);
            string? orderEst = Request.Form["OrderEst"];
            orderPrice = int.Parse(Request.Form["OrderPrice"]);
            expenseMachining = int.Parse(Request.Form["ExpenseMachining"]);

            if (barCageCount <= 50 && barCageCount >= 80)
            {
                TempData["exMessage"] = "Số nan phải lớn hơn 50 và nhỏ hơn 80 nan"; return Page();
            }
            else if (HttpContext.Session.GetString("userName") == null)
            {
                TempData["errorMessage"] = "Hãy đăng nhập tài khoản để được trải nghiệm tốt hơn";
                return RedirectToPage("/Login/Index");
            }

            int result = 0;
            if (_cartRepo.showCart().Count != 0) _cartRepo.clearCart();
            //add cageStyle to cart
            result = _cartRepo.addProductToCart(cageType, 1, 0);
            //add lidCage to cart
            result = _cartRepo.addProductToCart(lidCage, 1, 0);
            //add barCageType and Quantity to cart
            result = _cartRepo.addProductToCart(barCageType, barCageCount, 0);
            //add doorcageType to cart
            result = _cartRepo.addProductToCart(doorCageType, 1, 0);
            //add baseCage (đế của lồng) to cart
            result = _cartRepo.addProductToCart(baseCage, 1, 0);

            if (result == 0)
            {
                TempData["errorMessage"] = "Đưa vào danh sách giỏ hàng thất bại";
                return Page();
            }

            return RedirectToPage("./CheckoutCustomize", new { orderPrice = orderPrice, expMachining = expenseMachining, est = orderEst });
        }



    }
}

BirdCageShop/BirdCageShop/Pages/Users/UCart/Index.cshtml.cs
using BusinessObjects.Models;
using Humanizer.Localisation.TimeToClockNotation;
using MessagePack;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;

namespace BirdCageShop.Pages.Users.UCart
{
    public class IndexModel : PageModel
    {
        public string ErrorMessage {  get; set; }
        private readonly IUserRepository _usrRepo;
        private readonly ICartRepository _cartRepo;
        private readonly IOrderDetailRepository _odRepo;
        public decimal? totalCart { get; set; } = 0;
        public List<CartItem> cart { get; set; }
        public List<CartItem> cartItems { get; set; }
        
        public Order order { get; set; }
        public int quantity { get; set; }
        
        public IndexModel()
        {
            _usrRepo = new UserRepository();
            _cartRepo = new CartRepository();
            _odRepo = new OrderDetailRepository();

        }

        public void OnGet()
        {
            try
            {

                int userID = HttpContext.Session.GetInt32("userID").GetValueOrDefault(-1);
                if (userID == -1)
                {
                    TempData["errorMessage"] = "Đăng nhập để tiếp tục!";
                    RedirectToPage("../Login/Index");
                }
                _cartRepo.showCustomizeUserCageInCart(userID);
                var cartList = _cartRepo.showCart();
                if (cartList.Count != 0)
                {
                    cart = cartList.ToList();
                    order = _usrRepo.getOrderPrice_Cart_ByUserID(userID);
                    Page();
                }
                else
                {
                    cart = new List<CartItem>();
                    Page();
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "Đã có lỗi xảy ra. Chúng mình đang khắc phục. Lỗi : " + ex.Message;
                Page();
            }

        }

        public IActionResult OnPostDelete(int productID, int type)
        {
            try
            {
                int userID = HttpContext.Session.GetInt32("userID").GetValueOrDefault(-1);
                if (userID == -1)
                {
                    TempData["errorMessage"] = "Đăng nhập để tiếp tục!";
                    return RedirectToPage("../Login/Index");
                }
                else
                {
                    int result = _cartRepo.deleteProductfromCart(productID, type);
                    if (result != 0)
                    {
                        TempData["successMessage"] = "Xoá sản phẩm ra khỏi giỏ hàng của bạn thành công";
                        this.OnGet();
                        return Page();
                    }
                    else
                    {
                        TempData["errorMessage"] = "Xoá thất bại!. Đã có lỗi xảy ra";
                        return Page();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Website đang phát triển ! Xin lỗi vì sự bất tiện này! Lỗi: " + ex.Message + ". \nHãy liên hệ với quản trị viên";
                return Page();
            }

        }
        public void OnPostUpdate(int productID, int quantity, int type)
        {

            int userID = HttpContext.Session.GetInt32("userID").GetValueOrDefault(-1);
            if (userID == -1)
            {
                TempData["errorMessage"] = "Đăng nhập để tiếp tục!";
                     RedirectToPage("../Login/Index");
            }
            else if (_odRepo.isProductAvailble(quantity,productID,type) == true)
            {
                _cartRepo.updateQuantity(productID, quantity,type);
                OnGet();
                Page();
            }
            else
            {
                TempData["errorMessage"] = "Sản phẩm bạn vừa cập nhật không đủ số lượng ở cửa hàng";
                OnGet();
            }
            Page();
        }
    }
}

BirdCageShop/BirdCageShop/Pages/Users/UCart/Index.cshtml
@page "{handler?}"
@model BirdCageShop.Pages.Users.UCart.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Giỏ hàng";

}

@{

}
<body>
    @{
        var errorMessage = TempData["errorMessage"] as string;
        var successMessage = TempData["successMessage"] as string;
    }
    <div class="alert alert-danger" style="@(string.IsNullOrEmpty(errorMessage) ? "display: none;" : "")">
        @errorMessage
    </div>

    <!-- Hiển thị thông báo thành công -->
    <div class="alert alert-success" style="@(string.IsNullOrEmpty(successMessage) ? "display: none;" : "")">
        @successMessage
    </div>
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center"
             style="min-height: 300px;">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Giỏ hàng</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a asp-page="../Shop">Trang chủ</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Giỏ hàng</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->
    <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Sản phẩm</th>
                            <th>Giá</th>
                            <th>Số lượng</th>
                            <th>Tổng cộng</th>
                            <th>Xóa</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">

                        @foreach (var item in Model.cart)
                        {
                            <tr>
                                <td class="align-middle">
                                    <img src="img/product-1.jpg" alt="" style="width: 50px;" />
                                    @item.CageName
                                </td>

                                <td class="align-middle">@Html.Raw(item.DetailPrice.ToString("N0"))đ</td>
                                <td class="align-middle">
                                    <div class="input-group quantity mx-auto"
                                         style="width: 100px;">
                                        <form method="post" asp-page-handler="Update">
                                            @Html.AntiForgeryToken()
                                            <input name="productID" value="@item.Id" type="hidden" >
                                            <input name="type" value="@item.type" type="hidden">
                                            <input type="text"
                                                   class="form-control form-control-sm bg-secondary text-center myInput" oninput="myFunction(event)"
                                                   value="@item.DetailQuantity" name="quantity" />
                                            <a href="#" onclick="this.closest('form').submit();" class="myButton" style="display: none;">Lưu lại</a>
                                        </form>


                    
                                    </div>
                                </td>
                                @{
                                    // Check if quantity is null
                                    int quantity = 0;
                                    if (int.TryParse(item.DetailQuantity.ToString(), out int result))
                                    {
                                        quantity = result;
                                    }
                                    // Calculate total
                                    item.TotalPrice = 0;
                                    item.TotalPrice = item.DetailPrice * item.DetailQuantity;
                                    Model.totalCart += item.TotalPrice;
                                }
                                <td class="align-middle total">@Html.Raw(item.TotalPrice.ToString("N0"))đ</td>
                                <!--Delete button-->
                                <td class="align-middle">
                                    <form method="post" asp-route-productID="@item.Id" asp-route-type="@item.type" asp-page-handler="delete" id="deleteForm">
                                        <button class="btn btn-sm btn-primary" onclick="confirmDelete(event)">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </form>

                                </td>
                            </tr>
                        }
                    </tbody>
                    <div class="alert alert-danger">
                        Hãy lưu ý rằng số lượng sản phẩm mà bạn đã thêm vào giỏ hàng có thể đã hết hoặc không đủ số lượng.
                    </div>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-5" action="">
                    <div class="input-group">
                        <input type="text"
                               class="form-control p-4"
                               placeholder="Mã giảm giá" />
                        <div class="input-group-append">
                            <button class="btn btn-primary">Áp dụng mã giảm giá</button>
                        </div>
                    </div>
                </form>
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Tóm tắt giỏ hàng</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Tổng cộng</h6>
                            <h6 class="font-weight-medium">@Html.Raw(Model.totalCart.Value.ToString("N0"))đ</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Phí vận chuyển</h6>
                            <h6 class="font-weight-medium">@Html.Raw(10000.ToString("N0"))đ</h6>
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Tổng cộng</h5>
                            @{
                                Model.totalCart += 10000;
                            }
                            <h5 class="font-weight-bold">@Html.Raw(Model.totalCart.Value.ToString("N0"))đ</h5>
                        </div >

                        <a asp-page="../Checkout" class="btn btn-block btn-primary my-3 py-3">
                            Tiến hành thanh toán
                        </a> 
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Cart End -->
    <script>
        function myFunction(event) {
            var inputField = event.target;
            var saveButton = inputField.nextElementSibling;
            saveButton.style.display = 'inline';
        }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        function confirmDelete(event) {
            event.preventDefault();

            var confirmation = window.confirm("Bạn có muốn xoá sản phẩm này ra khỏi giỏ hàng? (Nếu sản phẩm tự tạo sẽ không lưu trong giỏ hàng của bạn)");

            if (confirmation) {
                document.getElementById("deleteForm").submit();
            }
        }
    </script>

</body>