BirdCageShop/BirdCageShop/Pages/Login/ConfirmRecover.cshtml.cs
using BusinessObjects;
using MailKit.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Exchange.WebServices.Data;
using MimeKit;
using Repository;
using static System.Net.WebRequestMethods;

namespace BirdCageShop.Pages.Login
{
    public class ConfirmRecoverModel : PageModel
    {
        private static readonly MailKit.Net.Smtp.SmtpClient smtpClient = new MailKit.Net.Smtp.SmtpClient();
        public string EmailRecover { get; set; }
        [BindProperty]
        public string OTP { get; set; }
        public int compareOTP { get; set; }
        private IUserRepository _user;
        private readonly IConfiguration _config;
        public ConfirmRecoverModel(IConfiguration config)
        {
            _user = new UserRepository();
            _config = config;
        }
        public void OnGet()
        {
        }
        /// <summary>
        /// Sent OTP email to User 
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostConfirmOTP()
        {
            EmailRecover = HttpContext.Session.GetString("email");
            compareOTP = (int)HttpContext.Session.GetInt32("OTP");
            int otpS = 0;
            if (!int.TryParse(OTP, out otpS))
            {
                otpS = 0;
            }
            
            if (otpS == compareOTP)
            {
                var user = _user.GetUserByEmail(EmailRecover);
                if (user == null)
                {
                    TempData["errorMessage"] = "Đã xảy ra lỗi. Không tìm thấy người dùng";
                    return RedirectToPage("./Index");
                }
                else
                {
                    string newPassword = Utility.passwordRecovery();
                    user.UserPassword = newPassword;
                    if (_user.UpdateUserPassword(user) != 0)
                    {
                        MimeMessage message = new MimeMessage();
                        message.From.Add(new MailboxAddress("CageShopWing", _config.GetSection("EmailUserName").Value));
                        message.To.Add(new MailboxAddress("", EmailRecover)); // Receiver's email
                        message.Subject = "CageShopWing - Mật khẩu đã được thay đổi";

                        message.Body = new TextPart("plain")
                        {
                            Text = $"Mật khẩu của bạn đã được thay đổi. Mật khẩu mới là:  {newPassword}. Hãy vui lòng truy cập tài khoản để thay đổi lại mật khẩu."
                        };

                        try
                        {
                            await smtpClient.ConnectAsync(_config.GetSection("EmailHost").Value, 587, SecureSocketOptions.StartTls); // Use the appropriate SMTP server and port
                            await smtpClient.AuthenticateAsync(_config.GetSection("EmailUserName").Value, _config.GetSection("EmailPassword").Value); // Your SMTP credentials
                            await smtpClient.SendAsync(message);
                            await smtpClient.DisconnectAsync(true);
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Error sending email: {ex.Message}");
                            TempData["errorMessage"] = "Đã xảy ra lỗi :" + ex.Message;
                            return Page();
                        }
                        TempData["successMessage"] = "Mật khẩu mới đã được gửi tới email. Hãy kiểm tra ở Hòm thư hoặc thư rác.";
                        HttpContext.Session.SetString("email", "");
                        HttpContext.Session.SetInt32("OTP", 0);
                        return RedirectToPage("./Index");
                    }
                    else
                    {
                        TempData["errorMessage"] = "Lưu mật khẩu mới thất bại! Không thể khôi phục";
                        return RedirectToPage("./Index");
                    }
                }

            }
            else
            {
                TempData["errorMessage"] = "Mã OTP không khớp!";
                OnGet();
                return Page();
            }
        }


    }
}

BirdCageShop/BirdCageShop/Pages/Login/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Exchange.WebServices.Autodiscover;
using Repository;

namespace BirdCageShop.Login
{
    public class IndexModel : PageModel
    {
        private readonly IUserRepository _userRepo;

        [BindProperty]
        public string Email { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public string ErrorMessage { get; set; }

        public IndexModel()
        {
            _userRepo = new UserRepository();
        }


        public IActionResult OnPost()
        {
            var user = _userRepo.checkUserLogin(Email, Password);
            if (user != null)
            {
                if (user.RoleId == 1)
                {
                    if (user.Status == "Suspended")
                    {
                        TempData["errorMessage"] = "Tài khoản của bạn đã bị hạn chế! Hãy liên hệ với Administrator";
                        return RedirectToPage("../Index");
                    }
                    else
                    {
                        HttpContext.Session.SetString("LoggedInUser", "User");
                        HttpContext.Session.SetString("userName", user.UserName);
                        HttpContext.Session.SetString("userEmail", user.Email);
                        HttpContext.Session.SetInt32("userID", user.UserId);
                        HttpContext.Session.SetInt32("Role", (int)user.RoleId);
                        return RedirectToPage("../Index");
                    }

                }
                else if (user.RoleId == 2)
                {
                    if (user.Status == "Suspended")
                    {
                        TempData["errorMessage"] = "Your account is banned! Contact Admin ASAP!";
                        return RedirectToPage("../Index");
                    }
                    else
                    {
                        HttpContext.Session.SetString("LoggedInUser", "Adminstrator");
                        return RedirectToPage("../Admin/MProduct/Index");
                    }

                }
                else if (user.RoleId == 3)
                {
                    
                    HttpContext.Session.SetString("LoggedInUser", "Shopkeeper");
                    return RedirectToPage("../Manager/MProduct/Index");
                }

                ///SA - SUPER ADMIN
                else if (user.RoleId == 4)
                {
                    HttpContext.Session.SetString("LoggedInUser", "Adminstrator");
                    return RedirectToPage("../Admin/MProduct/Index");
                }
                else
                {
                    TempData["errorMessage"] = "You are not allowed to do this function!";
                    return Page();
                }
            }
            else
            {
                TempData["errorMessage"] = "Wrong email or password! Try Again";
                return Page();
            }

        }
    }
}

BirdCageShop/BirdCageShop/Pages/Login/Recover.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repository;
using System.Net.Mail;
using System.Net;
using MailKit.Security;
using MimeKit;
using static System.Net.WebRequestMethods;
using BusinessObjects;
using MailKit.Net.Smtp;

namespace BirdCageShop.Pages.Login
{
    public class RecoverModel : PageModel
    {
        private static readonly MailKit.Net.Smtp.SmtpClient smtpClient = new MailKit.Net.Smtp.SmtpClient();
        [BindProperty]
        public string EmailRecover { get;set; }
        private IUserRepository _user;
        private readonly IConfiguration _config;
        public RecoverModel(IConfiguration config)
        {
            _user = new UserRepository();
            _config = config;
        }
        public void OnGet() 
        {
            Page();
        }

        public async Task<IActionResult> OnPostForgetPassword()
        {
            if(EmailRecover != null)
            {
                if(_user.isEmailexisted(EmailRecover))
                {
                    ///TODO: Send Email Check The code is == our system

                    int otp = Utility.codeRecovery();
                    MimeMessage message = new MimeMessage();
                    message.From.Add(new MailboxAddress("CageShopWing", _config.GetSection("EmailUserName").Value));
                    message.To.Add(MailboxAddress.Parse(EmailRecover)); // Receiver's email
                    message.Subject = "Khôi phục mật khẩu - CageShopWing";

                    message.Body = new TextPart("plain")
                    {
                        Text = $"Bạn đã gửi yêu khầu khôi phục mật khẩu. Mã xác thực là : {otp}. Nếu không phải bạn gửi yêu cầu hãy bỏ qua email này! Xin cảm ơn"
                    };

                    try
                    {
                        await smtpClient.ConnectAsync(_config.GetSection("EmailHost").Value, 587, SecureSocketOptions.StartTls); // Use the appropriate SMTP server and port
                        await smtpClient.AuthenticateAsync(_config.GetSection("EmailUserName").Value, _config.GetSection("EmailPassword").Value); // Your SMTP credentials
                        await smtpClient.SendAsync(message);
                        await smtpClient.DisconnectAsync(true);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error sending email: {ex.Message}");
                        TempData["errorMessage"] = "Đã xảy ra lỗi :" + ex.Message;
                        await smtpClient.DisconnectAsync(true);
                        return Page();
                    }

                    HttpContext.Session.SetString("email", EmailRecover);
                    HttpContext.Session.SetInt32("OTP", otp);
                    TempData["successMessage"] = "Mã OTP đã được gửi tới email. Hãy kiểm tra ở Hòm thư hoặc thư rác.";
                    return RedirectToPage("./ConfirmRecover");
                }
                else
                {
                    TempData["errorMessage"] = "Email bạn nhập không tồn tại!";
                    return Page();
                }
            }
            else
            {
                TempData["errorMessage"] = "Email bạn nhập không hợp lệ hoặc đang bỏ trống!";
                return Page();
            }
        }


    }
}

BirdCageShop/BirdCageShop/Pages/Login/ConfirmRecover.cshtml
@page
@model BirdCageShop.Pages.Login.ConfirmRecoverModel
@{
    ViewData["Title"] = "Xác nhận";
    Layout = "_Layout";
}
<head>
    <style>
        /* Form Login */
        #login-form {
            width: 600px;
            margin: 0 auto;
            background-color: #f2f2f2;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

            #login-form label {
                display: block;
                font-weight: bold;
                margin-bottom: 5px;
            }

            #login-form input[type="email"],
            #login-form input[type="password"] {
                width: 100%;
                padding: 10px;
                margin-bottom: 20px;
                border: none;
                border-radius: 5px;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            }

            #login-form button[type="submit"] {
                display: block;
                margin: 0 auto;
                background-color: #4caf50;
                color: #fff;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                cursor: pointer;
                transition: background-color 0.3s ease;
            }

                #login-form button[type="submit"]:hover {
                    background-color: #3e8e41;
                }
    </style>
</head>
<body>
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center"
             style="min-height: 300px;">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Gặp vấn đề đăng nhập?</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a asp-page="">Bạn đang gặp vấn đề với đăng nhập?</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Khôi phục mật khẩu</p>
            </div>
        </div>
        @{
            var errorMessage = TempData["errorMessage"] as string;
            var successMessage = TempData["successMessage"] as string;
            
        }
        
        <div class="alert alert-danger" style="@(string.IsNullOrEmpty(errorMessage) ? "display: none;" : "")">
            @errorMessage
        </div>

        <!-- Hiển thị thông báo thành công -->
        <div class="alert alert-success" style="@(string.IsNullOrEmpty(successMessage) ? "display: none;" : "")">
            @successMessage
        </div>

        <div></div>

        <form id="login-form" method="post" asp-page-handler="ConfirmOTP">
            <label for="email">Mã xác nhận </label>
            <input type="text" id="email" asp-for="@Model.OTP" required />
            <button type="submit">Xác thực</button>
            <br />
        </form>


        <br />
    </div>

</body>

BirdCageShop/BirdCageShop/Pages/Login/Index.cshtml
@page
@model BirdCageShop.Login.IndexModel
@{
    ViewData["Title"] = "Home page";
    //Set new layout here
    Layout = "_Layout";
    
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CodePen - CSS Cube Login Form</title>
    <link rel="stylesheet" href="~/css/style.css">
    <style>
        /* Form Login */
        #login-form {
            width: 400px;
            margin: 0 auto;
            background-color: #f2f2f2;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

            #login-form label {
                display: block;
                font-weight: bold;
                margin-bottom: 5px;
            }

            #login-form input[type="email"],
            #login-form input[type="password"] {
                width: 100%;
                padding: 10px;
                margin-bottom: 20px;
                border: none;
                border-radius: 5px;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            }

            #login-form button[type="submit"] {
                display: block;
                margin: 0 auto;
                background-color: #4caf50;
                color: #fff;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                cursor: pointer;
                transition: background-color 0.3s ease;
            }

                #login-form button[type="submit"]:hover {
                    background-color: #3e8e41;
                }
    </style>
</head>
<body>

    @{
        var errorMessage = TempData["errorMessage"] as string;
        var successMessage = TempData["successMessage"] as string;
    }
    <div class="alert alert-danger" style="@(string.IsNullOrEmpty(errorMessage) ? "display: none;" : "")">
        @errorMessage
    </div>

    <!-- Hiển thị thông báo thành công -->
    <div class="alert alert-success" style="@(string.IsNullOrEmpty(successMessage) ? "display: none;" : "")">
        @successMessage
    </div>
    <h1 style="text-align: center;">Đăng nhập</h1>
    <form id="login-form" method="post">
        <label for="email">Email:</label>
        <input type="email" id="email" asp-for="@Model.Email" required />

        <label for="password">Mật khẩu:</label>
        <input type="password" id="password" asp-for="@Model.Password" required />

        <button type="submit">Đăng nhập</button>
        <p style="text-align:center ;">
            Bạn chưa có tài khoản? Hãy <a asp-page="/Register/Index">Đăng ký</a>
        </p>
        <p style="text-align: center";>
            Bạn quên mật khẩu? Hãy <a asp-page="./Recover">Khôi phục mật khẩu</a>
        </p>
    </form> 

    <!-- partial -->

</body>
</html>

BirdCageShop/BirdCageShop/Pages/Login/Recover.cshtml
@page
@model BirdCageShop.Pages.Login.RecoverModel
@{
    ViewData["Title"] = "Khôi phục tài khoản";
    Layout = "_Layout";
}
<head>
    <style>
        /* Form Login */
        #login-form {
            width: 600px;
            margin: 0 auto;
            background-color: #f2f2f2;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

            #login-form label {
                display: block;
                font-weight: bold;
                margin-bottom: 5px;
            }

            #login-form input[type="email"],
            #login-form input[type="password"] {
                width: 100%;
                padding: 10px;
                margin-bottom: 20px;
                border: none;
                border-radius: 5px;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
            }

            #login-form button[type="submit"] {
                display: block;
                margin: 0 auto;
                background-color: #4caf50;
                color: #fff;
                border: none;
                border-radius: 5px;
                padding: 10px 20px;
                cursor: pointer;
                transition: background-color 0.3s ease;
            }

                #login-form button[type="submit"]:hover {
                    background-color: #3e8e41;
                }
    </style>
</head>
<body>
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center"
             style="min-height: 300px;">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Gặp vấn đề đăng nhập?</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a asp-page="">Bạn đang gặp vấn đề với đăng nhập?</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Khôi phục mật khẩu</p>
            </div>
        </div>
        @{
            var errorMessage = TempData["errorMessage"] as string;
            var successMessage = TempData["successMessage"] as string;
        }
        <div class="alert alert-danger" style="@(string.IsNullOrEmpty(errorMessage) ? "display: none;" : "")">
            @errorMessage
        </div>

        <!-- Hiển thị thông báo thành công -->
        <div class="alert alert-success" style="@(string.IsNullOrEmpty(successMessage) ? "display: none;" : "")">
            @successMessage
        </div>

        <div></div>

        <form id="login-form" method="post" asp-page-handler="ForgetPassword">
            <label for="email">Hãy nhập email đã đăng kí: </label>
            <input type="email" id="email" asp-for="@Model.EmailRecover" required />
            <button type="submit">Tìm kiếm</button>
            <br />
            <p style="text-align:center ;">
                Bạn chưa có tài khoản? Hãy <a asp-page="/Register/Index">Đăng ký</a>
            </p>
        </form>
        

        <br />
    </div>

</body>

BirdCageShop/BirdCageShop/Pages/Login/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Đăng nhập</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>